name: Keep Render Alive

on:
  schedule:
    - cron: '*/4 * * * *'
  workflow_dispatch: # يتيح لك تشغيلها يدوياً للتأكد من أنها تعمل

jobs:
  ping-server:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP request to website
        run: |
          curl -s https://kawahla.onrender.com/ > /dev/null
